# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'OmetriaSample' do
  use_frameworks!

  pod 'Ometria', :git => 'https://github.com/Ometria/ometria.ios_sdk.git'
  
  target 'OmetriaSampleNotificationService' do
    pod 'Ometria', :git => 'https://github.com/Ometria/ometria.ios_sdk.git'
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'Ometria'
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
      end
    end
  end
end

