# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

def shared_pods
  pod 'Ometria', :git => 'https://github.com/Ometria/ometria.ios_sdk.git'
end

target 'OmetriaSample' do
  use_frameworks!
  shared_pods
end

target 'OmetriaSampleNotificationService' do
  use_frameworks!
  shared_pods
end

target 'OmetriaSampleTests' do
  use_frameworks!
  shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
#    if target.name == 'Ometria'
#      target.build_configurations.each do |config|
#        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
#      end
#    end
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.2'
    end
  end
end
